---

- hosts: localhost

  roles:
    - { role: packages, become: yes, become_method: sudo }
    - ohmyzsh
    - my-dotfiles
    - { role: pablocrivella.nvm, become: yes, become_method: sudo }
    - meteor
